financial_intelligence:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: C:/Users/gazal/Desktop/Personal Projects/Canadian_Market_Intel/financial_db.duckdb
      schema: marts
      threads: 4